# subworkflow: slides
#
# Contributors: @lachlandeer, @julianlanger

# --- Importing Configuration Files --- #

configfile: "../../" "config.yaml"

ROOT = config["sub2root"]
HERE = ROOT + config["src_slides"]
LIB  = ROOT + config["src_lib"]
OUT  = config["out"]

# --- Sub Workflow Dependencies --- #
subworkflow figures:
    workdir:  ROOT + config["ROOT"]
    snakefile: ROOT + config["src_figures"] + "Snakefile"

subworkflow tables:
    workdir:   ROOT + config["ROOT"]
    snakefile: ROOT + config["src_tables"] + "Snakefile"

# --- Build Rules --- #

## build_beamer: knit beamer slides
rule build_beamer:
    input:
        runner    = LIB + "knit_beamer.R",
        rmd_file  = HERE + "slides.Rmd",
        tables     = tables(config["out_tables"] +
                        "tab02_augment_solow.tex"),
        figures = figures(config["out_figures"] +
                            "unconditional_convergence.pdf"),
    output:
        pdf = Path(ROOT) / config["out_slides"] / "slides.pdf"
    log:
        ROOT + config["log"]+ "slides/slides.Rout"
    shell:
        "{runR} {input.runner} {input.rmd_file} {output.pdf} \
            > {log} {logAll}"
