# subworkflow - figures
#
# @yourname
#

# --- Importing Configuration Files --- #

configfile: "config.yaml"

# --- Sub Workflows --- #
subworkflow data_mgt:
   workdir: config["sub2root"] + config["ROOT"]
   snakefile: config["sub2root"] + config["src_data_mgt"] + "Snakefile"

# --- Build Rules --- #
## make_figs          : builds all figures
rule make_figs:
    input:
        expand(config["out_figures"] + "{iFigure}.pdf",
                iFigure = FIGURES)

## figures            : recipe for constructing a figure (cannot be called)
rule figures:
    input:
        script = config["src_figures"] + "{iFigure}.R",
        data   = data_mgt(config["out_data"] + "mrw_complete.csv"),
        subset = config["src_data_specs"] + "subset_intermediate.json"
    output:
        fig = Path(config["out_figures"]) / "{iFigure}.pdf"
    log:
        config["log"]+ "figures/{iFigure}.Rout"
    shell:
        "Rscript {input.script} \
            --data {input.data} \
            --subset {input.subset} \
            --out {output.fig} \
            > {log} 2>&1"
